AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: awsdev capstone

Globals:
  Function:
    Runtime: python3.11
    Timeout: 15

Resources:
  Bucket:
    Type: AWS::S3::Bucket

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [!Ref Queue]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt Queue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:s3:::${Bucket}

  BucketNotification:
    Type: AWS::S3::BucketNotification
    Properties:
      Bucket: !Ref Bucket
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt Queue.Arn
    DependsOn: QueuePolicy

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  Worker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: worker.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
            BatchSize: 5

  Api:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: api.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
      Events:
        Get:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: get

Outputs:
  BucketName:
    Value: !Ref Bucket
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items"
