AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: awsdev sam app

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10

Resources:
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        Get:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: get
        Put:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: put
