AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: awsdev lambda event source (sqs)

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10
    MemorySize: 128

Resources:
  DemoQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 30

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.handler
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt DemoQueue.Arn
            BatchSize: 5

Outputs:
  QueueUrl:
    Value: !Ref DemoQueue
