AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: awsdev URL shortener (SAM)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    Environment:
      Variables:
        TABLE_NAME: !Ref LinksTable

Resources:
  LinksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: shorten.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LinksTable
      Events:
        Shorten:
          Type: Api
          Properties:
            Path: /shorten
            Method: post

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: redirect.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LinksTable
      Events:
        Redirect:
          Type: Api
          Properties:
            Path: /{code}
            Method: get

  StatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: stats.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref LinksTable
      Events:
        Stats:
          Type: Api
          Properties:
            Path: /stats/{code}
            Method: get

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  TableName:
    Value: !Ref LinksTable
